config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => { :registrations => 'users/registrations', :invitations => 'users/invitations' }

  resource :company do
    member do
      get :search_invoices
      get :about
      delete 'delete_user/:id', to: 'companies#delete_user', as: :delete_user
    end
  end

  get :dashboard, to: 'dashboard#home'
  get 'dashboard/developer', as: :developer_dashboard
  get 'dashboard/developer/:all_users', to: 'dashboard#developer', as: :all_users

  resources :accounts do
    post :invite_customer, on: :member
  end

  resources :services, except: [:show, :index, :new] do
    collection do
      post :dashboard_create
      post :invoice_create
      get :history_search
    end
  end

  resources :invoices do
    collection do
      post :apply_checked_services_create
    end
    member do
      get :invoice_ready
      patch :change_account_header
      patch :apply_services_update
      patch :remove_services_update
    end
    resources :payments, except: [:show, :index]
  end

  resources :reports, only: [:index] do
    collection do
      get :income
      get 'income/accounts', to: 'reports#income_accounts'
      get 'income/line_graph', to: 'reports#income_line_graph'
      get 'income/bar_graph', to: 'reports#income_bar_graph'
    end
  end

  resources :inventory_items
  get 'search_tag/:tag', to: 'inventory_items#index', as: :tag

  get :about, to: 'welcome#about'
  get :contact_us, to: 'welcome#contact_us'
  get 'sitemap.xml', to: 'welcome#sitemap', format: :xml, as: :sitemap

  root to: 'welcome#home'
end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :company
  
  # Keeping belongs_to, accepts_nested_attrubtes_for and attr_accessible all
  # in one place because they are all related to the User.
  belongs_to :user, dependent: :delete
  accepts_nested_attributes_for :user

  has_many :services, dependent: :destroy
  has_many :invoices, dependent: :destroy
  has_many :payments

  validates :name, presence: true
  validate :company_account_name_unique

  scope :by_name, -> { order('name ASC') }
  scope :by_recent_activity, -> { order('updated_at DESC') }
  scope :with_limit, -> { limit(5) }

  def full_address
    [address_1, address_2, city, state, zip].select(&:present?).join(', ')
  end

  def sum_services(view_by, active_date)
    services.by_selected_range(view_by, active_date).sum(:cost)
  end

  def sum_invoiceable_services
    services.by_invoiceable.sum(:cost)
  end

  def total_account_payments(view_by, active_date)
    payments.by_selected_range(view_by, active_date).sum(:amount)
  end

  def all_services_invoiced?
    !services.by_invoiceable.present?
  end

  def paid_in_full?
    invoices.all?(&:paid_in_full?)
  end

  def total_outstanding_invoices
    invoices.by_outstanding.sum(&:balance_due)
  end

private

  # Check for Company Account name uniqueness.
  def company_account_name_unique
    errors.add(:name, 'already exists') if name && account_name_exists?
  end

  # If account is being updated, find the current account the user is updating and remove that account's name
  # from the array. Then check if the form [name] being submitted is present. This allows account to be updated
  # while validating the form [name] submitted is unique.
  # If account is being created, there is no [id], and no names will be removed from the array.
  def account_name_exists?
    (company.accounts.pluck(:name) - [current_account.try(:name)]).include?(name)
  end

  # Use find_by :id method so if there is no [id] present, current_account returns nil.
  def current_account
    @current_account ||= company.accounts.find_by(id: self.id)
  end
end

app/models/service.rb
class Service < ActiveRecord::Base

  before_validation { |service| service.cost = 0 if service.cost.blank? }

  belongs_to :account, touch: true, optional: true
  belongs_to :invoice, optional: true
  belongs_to :company, optional: true

  validates :cost, numericality: true
  validates :performed_on,
            format: { with: /\A(?<year>\d{4})\-(?<month>\d{1,2})\-(?<day>\d{1,2})\z/,
                      message: 'date must be formatted correctly (yyyy-mm-dd)' }

  include SelectedRange
  # def by_selected_range(view_by, active_date)
  #   time_range = (active_date.send("beginning_of_#{view_by}")..active_date.send("end_of_#{view_by}"))
  #   where(:performed_on => time_range)
  # end

  default_scope { order('performed_on DESC') }

  scope :by_invoiceable, -> { where(invoice_id: nil) }
  scope :with_limit, -> { limit(5) }

  def disable_link_if_archived?
    'disable_link gray_text' if invoice_id.present? && invoice.payments.any?
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin!, except: [:history_search]
  before_action :require_no_payments!, only: [:edit, :update, :destroy]

  def create
    @account = current_account
    @services = current_account.services
    @service = current_account.services.build(service_params)
    @service.company = current_company
    @invoice = current_account.invoices.build
    @invoices = @account.invoices.by_outstanding

    if @service.save
      redirect_to current_account, notice: 'Service was successfully created.'
    else
      render 'accounts/show'
    end
  end

  # Create a new service from the admin dashboard
  def dashboard_create
    @account = current_company.accounts.find(params[:service][:account_id])
    @service = @account.services.build(service_params)
    @service.company = current_company
    @accounts = current_company.accounts.by_recent_activity.with_limit

    if @service.save
      set_current_account_after_save(@account.id)
      redirect_to dashboard_path, notice: "Service was successfully created for #{@account.name} Account."
    else
      render 'dashboard/home'
    end
  end

  def invoice_create
    @invoice = current_account.invoices.friendly.find(params[:invoice_id])
    @service = current_account.services.build(service_params)
    @service.company = current_company
    @service.invoice = @invoice
    @services = current_account.services

    if @service.save
      redirect_to edit_invoice_path(@invoice), notice: 'Service was successfully created.'
    else
      render 'invoices/edit'
    end
  end

  def edit
  end

  def update
    if @service.update_attributes(service_params)
      redirect_to_account_or_invoice
    else
      render :edit
    end
  end

  def destroy
    @service.destroy

    redirect_to current_account, alert: 'Service history item successfully deleted.'
  end

  def history_search
    @services = current_account.services.by_selected_range(view_by, active_date).page(params[:page]).per(20).includes(invoice: [:account, :payments])
  end

private

  # Never trust parameters from the scary internet, only allow the white list through.
  def service_params
    params.require(:service).permit(:memo, :performed_on, :cost)
  end

  def redirect_to_account_or_invoice
    if params[:invoice_id] && !@service.invoice.nil?
      redirect_to edit_invoice_path(@service.invoice), notice: 'Service was successfully updated.'
    else
      redirect_to current_account, notice: 'Service was successfully updated.'
    end
  end

  def require_no_payments!
    @service = current_account.services.find(params[:id])
    @invoice = @service.invoice

    redirect_to @invoice, alert: 'SERVICES can only be EDITED or DELETED when no payments are applied!' if @service.invoice_id.present? && @invoice.payments.any?
  end
end

app/helpers/services_helper.rb
module ServicesHelper
  def year_or_month_select
    case view_by
    when :month
      select_date(active_date, discard_day: true)
    else
      select_date(active_date, discard_month: true, discard_day: true)
    end
  end
end

app/views/services/_date_bar_forms.html.haml
= form_tag history_search_services_path, class: :view_by_selection, method: :get do
  .row
    / View By Form
    .small-12.medium-6.columns
      %label Search by:
      %ul.inline-list
        %li
          %label
            = radio_button_tag 'view_by', :month, view_by == :month
            Month
        %li
          %label
            = radio_button_tag 'view_by', :year, view_by == :year
            Year
        %li= submit_tag 'View By', class: 'tiny button radius', name: nil

    / Active Date Form
    = form_tag history_search_services_path, class: :view_by_selection, method: :get do
      .small-6.medium-3.columns
        = year_or_month_select

      .small-6.medium-3.columns
        = submit_tag "Select #{view_by.to_s.capitalize} to View", class: 'tiny button radius', name: nil

app/views/services/_fields.html.haml
.row
  .small-12.medium-6.large-6.columns
    = f.label :performed_on, 'Performed on (yyyy-mm-dd)'
    = f.text_field :performed_on, class: 'datePicker', placeholder: 'Date'

  .small-12.medium-6.large-6.columns
    = f.label :cost
    .input-group
      %span.input-group-label $
      = f.number_field :cost, step: 0.01, placeholder: '0.00', class: 'input-group-field'

.row
  .small-12.medium-6.large-6.columns
    = f.label :memo
    = f.text_field :memo

  .small-12.medium-6.large-6.columns
    = f.submit class: 'small button small_button_down radius expanded'

app/views/services/_form.html.haml
.row
  .small-12.columns
    = form_for @service do |f|
      = render 'shared/error_messages', object: f.object
      = hidden_field_tag :invoice_id, @service.invoice_id if params[:invoice_id] && !@service.invoice.nil?

      = render 'services/fields', f: f

app/views/services/_history_table.html.haml
.scroll_overflow-x
  %table
    %thead
      %tr
        %th Invoice#
        %th Performed on
        %th Memo
        %th Cost
        - if current_user.is_admin?
          %th Edit
          %th Delete

    %tbody
      - @services.each do |service|
        - if service.persisted?
          = render 'services/history_table_row', service: service

= paginate @services

app/views/services/_history_table_row.html.haml
%tr
  %td
    - if service.invoice_id.present?
      = link_to invoice_path(service.invoice) do
        %i.fas.fa-file
        %b= service.invoice.pre_post_number
    - else
      %i not invoiced
  %td= service.performed_on.strftime('%Y-%b-%d')
  %td= service.memo
  %td= number_to_currency(service.cost, unit: '$')
  - if current_user.is_admin?
    %td.center_cell
      = link_to edit_service_path(service), class: service.disable_link_if_archived? do
        %i.fas.fa-edit
    %td.center_cell
      = link_to service, class: "#{service.disable_link_if_archived?} red_link", method: :delete,
      data: { confirm: t(:confirm_delete_service) } do
        %i.fas.fa-trash

app/views/services/_index.html.erb
<h4>Service History Search</h4>

<%= render 'services/date_bar_forms' %>

<div class="row">
  <div class="small-12 columns total_amount">
    <label>
      <%= "Cost of Services this #{view_by.capitalize}:" %>
      <span><%= number_to_currency(@account.sum_services(view_by, active_date)) %></span>
    </label>
  </div>
</div>

<table>
  <thead>
  <tr>
    <th>Invoice#</th>
    <th>Performed on</th>
    <th>Memo</th>
    <th>Cost</th>
    <% if current_user.is_admin? %>
      <th>Edit</th>
      <th>Delete</th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% services_with_view_by_scope(@services).each do |service| %>
    <% if service.persisted? %>
      <tr>
        <td>
          <% if service.invoice_id.present? %>
            <%= link_to invoice_path(service.invoice_id) do %>
              <i class="page fi-page"> <b><%= service.invoice_id %></b></i>
            <% end %>
          <% else %>
            <i>not invoiced</i>
          <% end %>
        </td>
        <td><%= service.performed_on.strftime('%Y-%b-%d') %></td>
        <td>
          <% if service.memo.length > 20 %>
            <%= link_to '#', 'data-reveal-id' => "memoModal#{service.id}", remote: true do %>
              <%= service.memo.truncate(20, :omission => '...') %>
            <% end %>
            <%= render 'services/memo_modal', service: service %>
          <% else %>
            <%= service.memo %>
          <% end %>
        </td>
        <td><%= number_to_currency(service.cost, unit: '$') %></td>
        <% if current_user.is_admin? %>
          <td class="center_cell">
            <%= link_to edit_service_path(service) do %>
              <i class="page fi-page-edit"></i>
            <% end %>
          </td>
          <td class="center_cell">
            <%= link_to service,
                        method: :delete,
                        confirm: 'Are you sure? This will permanently DELETE your SERVICE history record!' do %>
              <i class="general fi-x"></i>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/services/_invoiceable.html.haml
#invoiceable.anchor
.outline
  .row
    .small-12.medium-6.large-6.columns
      %h4 Invoiceable Services
    .small-12.medium-6.large-6.columns
      %label
        Invoiceable Total:
        %span.large_red_text= number_to_currency(@account.sum_invoiceable_services)
      %br/

  = render 'services/invoiceable_form'

app/views/services/_invoiceable_form.html.haml
= form_for @invoice, url: invoice_services_path, method: :patch do |f|

  = render 'shared/error_messages', object: f.object

  = render 'services/date_tax_fields', f: f

  .scroll_overflow-x
    %table
      %thead
        %tr
          - if current_user.is_admin?
            %th Invoice?
          %th Performed on
          %th Memo
          %th Cost
          - if current_user.is_admin?
            %th Edit
            %th Delete

      %tbody
        - @services.by_invoiceable.each do |service|
          - if service.persisted?
            %tr
              - if current_user.is_admin?
                %td= check_box_tag 'service_ids[]', service.id, service.invoice_id.nil?
              %td= service.performed_on.strftime('%Y-%b-%d')
              %td= service.memo
              %td= number_to_currency(service.cost, unit: '$')
              - if current_user.is_admin?
                %td.center_cell
                  = link_to edit_service_path(service) do
                    %i.page.fi-page-edit
                %td.center_cell
                  = link_to service, method: :delete,
                  data: { confirm: 'Are you sure? This will permanently DELETE your SERVICE history record!' } do
                    %i.general.fi-x

  = f.submit 'Invoice Checked Services', class: 'tiny button radius' if current_user.is_admin?

app/views/services/_note.html.erb
<div <%= "id=noteModal#{service.id}" %> class="reveal-modal" data-reveal>
  <h1><%= current_account.name %> Note <small><%= service.performed_on %></small></h1>

  <p><%= service.note %></p>

  <% if current_user.is_admin? %>
    <%= link_to 'Edit', edit_service_path(service), class: 'small button radius' %>
  <% end %>

  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/services/_recent_history.html.haml
.outline
  %h4 Recent Service History

  .scroll_overflow-x
    %table
      %thead
        %tr
          %th Invoice#
          %th Performed on
          %th Memo
          %th Cost
          - if current_user.is_admin?
            %th Edit
            %th Delete

      %tbody
        - @services.with_limit.each do |service|
          - if service.persisted?
            = render 'services/history_table_row', service: service

  .label_size= link_to "#{current_account.name} Service History Search", history_search_services_path

app/views/services/_services.html.erb
<h4>Invoiceable Services</h4>

<div class="row">
  <div class="small-12 columns total_amount">
    <label>
      Invoiceable Amount:
      <span><%= number_to_currency(@account.sum_invoiceable_services) %></span>
    </label>
  </div>
</div>

<%= form_tag invoice_services_path, method: :put do %>
  <table>
    <thead>
      <tr>
        <% if current_user.is_admin? %>
          <th>Invoice</th>
        <% end %>
        <th>Performed on</th>
        <th>Cost</th>
        <th>Note</th>
        <% if current_user.is_admin? %>
          <th>Edit</th>
          <th>Delete</th>
        <% end %>
      </tr>
    </thead>

    <tbody>
    <% @services.by_not_used.each do |service| %>
      <% if service.persisted? %>
        <tr>
          <% if current_user.is_admin? %>
            <td><%= check_box_tag 'service_ids[]',
                                  service.id,
                                  service.invoice_id.nil?,
                                  disabled: service.invoice_id? %></td>
          <% end %>
          <td><%= service.performed_on.strftime('%Y-%b-%d') %></td>
          <td><%= number_to_currency(service.cost, unit: '$') %></td>
          <td>
            <% if service.note.length > 10 %>
              <%= link_to '#', 'data-reveal-id' => "noteModal#{service.id}", remote: true do %>
                <%= service.note.truncate(10, :omission => '... (continued)') %>
              <% end %>
              <%= render 'services/note_modal', service: service %>
            <% else %>
              <%= service.note %>
            <% end %>
          </td>
          <% if current_user.is_admin? %>
            <td class="center_cell">
              <%= link_to edit_service_path(service) do %>
                <i class="page fi-page-edit"></i>
              <% end %>
            </td>
            <td class="center_cell">
              <%= link_to service,
                          method: :delete,
                          confirm: 'Are you sure? This will permanently DELETE your SERVICE history record!' do %>
                <i class="general fi-x"></i>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
  <%= submit_tag 'Invoice Checked Services', class: 'tiny button radius' if current_user.is_admin? %>
<% end %>

app/views/services/edit.html.haml
- provide(:title, 'Edit Service')

.row
  .small-12.columns
    %h1.main_page_header Editing Service
    .panel
      = render 'form'
      = link_to "#{current_account.name} Account", current_account, class: 'small button radius'

app/views/services/history_search.html.haml
- provide(:title, raw("#{current_account.name} Account - Service History"))

.row
  .small-12.columns
    %br/

    .outline= render 'accounts/edit_customer_header'
.row
  .small-12.columns
    .outline
      %h4 Service History Search
      = render 'services/date_bar_forms'

      .row
        .small-12.columns.total_amount
          %label
            = "Total Cost of Services for the Selected #{view_by.capitalize}:"
            %span.large_red_text= number_to_currency(current_account.sum_services(view_by, active_date))
      .row
        .small-12.columns
          = render 'services/history_table'

    %br/

    %ul.inline-list
      %li= link_to "#{current_account.name} Account", current_account, class: 'small button radius'
      %li= link_to "#{current_account.name} Invoices", invoices_path, class: 'small button radius'

app/views/services/search_history.html.haml
- provide(:title, raw("#{@account.name} Account - Service History"))

.row
  .small-12.columns
    %br/

    .outline= render 'accounts/edit_customer_header'

    .outline
      %h4 Service History Search
      = render 'services/date_bar_forms'

      .row
        .small-12.columns.total_amount
          %label
            = "Cost of Services this #{view_by.capitalize}:"
            %span.large_red_text= number_to_currency(current_account.sum_services(view_by, active_date))

      = render 'services/history_table'

    %br/

    %ul.inline-list
      %li= link_to "#{@account.name} Account", current_account, class: 'small button radius'
      %li= link_to "#{@account.name} Invoices", invoices_path, class: 'small button radius'