config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => { :registrations => 'users/registrations', :invitations => 'users/invitations' }

  resource :company do
    member do
      get :search_invoices
      get :about
      delete 'delete_user/:id', to: 'companies#delete_user', as: :delete_user
    end
  end

  get :dashboard, to: 'dashboard#home'
  get 'dashboard/developer', as: :developer_dashboard
  get 'dashboard/developer/:all_users', to: 'dashboard#developer', as: :all_users

  resources :accounts do
    post :invite_customer, on: :member
  end

  resources :services, except: [:show, :index, :new] do
    collection do
      post :dashboard_create
      post :invoice_create
      get :history_search
    end
  end

  resources :invoices do
    collection do
      post :apply_checked_services_create
    end
    member do
      get :invoice_ready
      patch :change_account_header
      patch :apply_services_update
      patch :remove_services_update
    end
    resources :payments, except: [:show, :index]
  end

  resources :reports, only: [:index] do
    collection do
      get :income
      get 'income/accounts', to: 'reports#income_accounts'
      get 'income/line_graph', to: 'reports#income_line_graph'
      get 'income/bar_graph', to: 'reports#income_bar_graph'
    end
  end

  resources :inventory_items
  get 'search_tag/:tag', to: 'inventory_items#index', as: :tag

  get :about, to: 'welcome#about'
  get :contact_us, to: 'welcome#contact_us'
  get 'sitemap.xml', to: 'welcome#sitemap', format: :xml, as: :sitemap

  root to: 'welcome#home'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_developer!, only: [:developer]
  before_action :load_current_account, only: [:home]

  # both admin and customer users dashboard
  def home
    @accounts = current_company.accounts.by_recent_activity.with_limit.includes(:invoices, :user)
    @service = current_company.services.build
    @service.performed_on ||= Date.current
  end

  def developer
    @users = Kaminari.paginate_array(admins_or_all_users.includes(:company).sort_by(&:company_id)).page(params[:page]).per(20)
  end

private

  def authenticate_developer!
    redirect_to root_path unless current_user.email == ENV['DEVELOPER_EMAIL']
  end

  # developer can view admin users or all users
  def admins_or_all_users
    params[:all_users] ? User.all : User.by_admin_user
  end

  def load_current_account
    if current_account
      @account = current_account
      @services = current_account.services.includes(invoice: :account)
      @invoices = current_account.invoices.by_outstanding
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
  # Change link according to the view the developer has requested
  def admin_or_all_users
    if params[:all_users]
      link_to 'Show only admin users', developer_dashboard_path
    else
      link_to 'Show all users', all_users_path(:all_users)
    end
  end
end

app/views/dashboard/_admin_view.html.haml
.row
  .small-12.columns
    %br/

    - unless @accounts.any?
      .alert-box.warning.radius
        Be sure to #{link_to 'edit your company', edit_company_path} information to add your
        logo, address, phone number, set your regional sales tax, ect., that will be applied to your invoice headers.
        %br/
        After that feel free to #{link_to 'create you first account', new_account_path}.

    .outline
      - if current_user.is_owner?
        .float-right
          = link_to edit_company_path, title: 'Edit Company' do
            Edit
            %i.fas.fa-edit

      = render 'companies/header_preview'

    = render 'dashboard/recent_accounts'

    = render 'dashboard/new_service'

    = render 'dashboard/overview'

app/views/dashboard/_customer_view.html.haml
.row
  .small-12.columns
    %br/

    .outline
      = render 'companies/header'

    .outline
      .row
        .small-8.columns
          %h4 Your contact information
        .small-4.columns
          = link_to edit_account_path(current_account) do
            .pad-top.right
              Edit
              %i.fas.fa-edit
      .row
        .small-12.columns
          = render 'shared/customer_header'

    = render 'invoices/outstanding' unless @account.paid_in_full?

    = render 'services/recent_history'

app/views/dashboard/_new_service.haml
.outline
  %p
    %b New Service
  = form_for @service, url: services_dashboard_create_path, method: :post do |f|
    = render 'shared/error_messages', object: f.object

    .row
      .small-12.columns
        = f.label :account_id, 'Select Account'
        = f.collection_select :account_id, current_company.accounts, :id, :name

    .row
      .small-12.medium-6.large-6.columns
        = f.label :performed_on, 'Performed on (yyyy-mm-dd)'
        = f.text_field :performed_on, class: 'datePicker', placeholder: 'Date'

      .small-12.medium-6.large-6.columns
        = f.label :cost
        .row.collapse
          .small-3.medium-2.large-2.columns
            %span.prefix $
          .small-9.medium-10.large-10.columns
            = f.number_field :cost, step: 0.01, placeholder: '0.00'

    .row
      .small-12.medium-6.large-6.columns
        = f.label :memo
        = f.text_field :memo

      .small-12.medium-6.large-6.columns
        = f.submit class: 'small button small_button_down radius expand'

app/views/dashboard/_new_service.html.haml
.outline
  %h4 New Service
  = form_for @service, url: dashboard_create_services_path, method: :post do |f|
    = render 'shared/error_messages', object: f.object

    .row
      .small-12.medium-12.large-6.columns
        = f.label :account_id do
          Select Existing Account or
          = link_to 'Create New Account', new_account_path
        = f.collection_select :account_id, @accounts.by_name, :id, :name

    .row
      .small-12.medium-6.large-6.columns
        = f.label :performed_on, 'Performed on (yyyy-mm-dd)'
        = f.text_field :performed_on, class: 'datePicker', placeholder: 'Date'

      .small-12.medium-6.large-6.columns
        = f.label :cost
        .input-group
          %span.input-group-label $
          = f.number_field :cost, step: 0.01, placeholder: '0.00', class: 'input-group-field'


    .row
      .small-12.medium-6.large-6.columns
        = f.label :memo
        = f.text_field :memo

      .small-12.medium-6.large-6.columns
        = f.submit class: 'small button small_button_down radius expanded'

app/views/dashboard/_overview.html.haml
.outline
  %h4 Overview of #{Date.current.strftime('%B')}

  .row
    .small-12.columns
      .label_size
        %b Company Accounts:
        = @accounts.count

  .row
    .small-12.columns
      = content_tag :div, '', id: 'moneyHealth', style: 'width:100%; height:200px;',
      data: { amounts: current_company.money_health(:month, Date.current) }

  .label_size= link_to 'View company reports', reports_path

app/views/dashboard/_recent_accounts.html.haml
.outline
  %h4
    Accounts
    %small - Recent Activity

  = render 'accounts/table' if @accounts.any?

  .label_size
    = link_to 'View All Accounts', accounts_path
    or
    = link_to'Create New Account', new_account_path

app/views/dashboard/_users_table.html.haml
.row
  .small-12.columns
    .scroll_overflow-x
      %table
        %thead
          %tr
            %th Admin User Name
            %th Email
            %th ID
            %th Comp ID
            %th Owner
            %th Admin
            %th Sign in count
            %th Last sign in at
        %tbody
          - @users.group_by(&:company).each do |company, users|
            %tr.subject
              %td{colspan: 8}
                %b Company name:
                = company.name
                \| # of accounts
                = surround '"' do
                  = company.accounts.count

            - for user in users
              %tr
                %td= user.name
                %td= user.email
                %td= user.id
                %td= user.company_id
                %td= yes_or_no(user.is_owner?)
                %td= yes_or_no(user.is_admin?)
                %td= user.sign_in_count unless user.sign_in_count.nil?
                %td= user.last_sign_in_at.strftime('%Y-%b-%d @ %I:%M%p') unless user.last_sign_in_at.nil?

app/views/dashboard/developer.html.haml
- provide(:title, 'Developer Dashboard')

.row
  .medium-5.columns
    = image_pack_tag 'TinFoilHat.svg'
.row
  .small-12.columns
    %h1.main_page_header DeveloperDashboard
    %br/

    %h3 Users
    %ul.no_bullets
      %li
        Number of users:
        %b= User.all.count
      %li
        Number of company owners:
        %b= User.by_owner_user.count
  %hr/

.row
  .small-6.columns
    %b= params[:all_users] ? 'Viewing all users' : 'Only viewing Admins'
    |
    = admin_or_all_users

%br/

= render 'users_table'

.row
  .small-12.columns
    = paginate @users

app/views/dashboard/home.html.haml
- provide(:title, 'Dashboard')

= render "dashboard/#{current_user.role}_view"

app/views/dashboard/index.html.haml
- provide(:title, 'Dashboard')

= render "dashboard/#{current_user.role}_view"