config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => { :registrations => 'users/registrations', :invitations => 'users/invitations' }

  resource :company do
    member do
      get :search_invoices
      get :about
      delete 'delete_user/:id', to: 'companies#delete_user', as: :delete_user
    end
  end

  get :dashboard, to: 'dashboard#home'
  get 'dashboard/developer', as: :developer_dashboard
  get 'dashboard/developer/:all_users', to: 'dashboard#developer', as: :all_users

  resources :accounts do
    post :invite_customer, on: :member
  end

  resources :services, except: [:show, :index, :new] do
    collection do
      post :dashboard_create
      post :invoice_create
      get :history_search
    end
  end

  resources :invoices do
    collection do
      post :apply_checked_services_create
    end
    member do
      get :invoice_ready
      patch :change_account_header
      patch :apply_services_update
      patch :remove_services_update
    end
    resources :payments, except: [:show, :index]
  end

  resources :reports, only: [:index] do
    collection do
      get :income
      get 'income/accounts', to: 'reports#income_accounts'
      get 'income/line_graph', to: 'reports#income_line_graph'
      get 'income/bar_graph', to: 'reports#income_bar_graph'
    end
  end

  resources :inventory_items
  get 'search_tag/:tag', to: 'inventory_items#index', as: :tag

  get :about, to: 'welcome#about'
  get :contact_us, to: 'welcome#contact_us'
  get 'sitemap.xml', to: 'welcome#sitemap', format: :xml, as: :sitemap

  root to: 'welcome#home'
end

app/models/inventory_item.rb
class InventoryItem < ActiveRecord::Base

  before_validation { |inventory_item| inventory_item.quantity = 0 if inventory_item.quantity.blank? }

  belongs_to :company

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :description, presence: true
  validates :quantity, numericality: true

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      company.tags.where(name: n.strip.downcase).first_or_create!
    end
  end
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin!

  def index
    if params[:tag]
      @inventory_items = current_company.tagged_with(params[:tag]).page(params[:page]).per(20)
    else
      @inventory_items = current_company.inventory_items.page(params[:page]).per(20)
    end
  end

  def show
    @inventory_item = current_company.inventory_items.find(params[:id])
  end

  def new
    @inventory_item = current_company.inventory_items.new
  end

  def create
    @inventory_item = current_company.inventory_items.new(inventory_item_params)

    if @inventory_item.save
      redirect_to inventory_items_path, notice: 'Inventory was successfully created.'
    else
      render :new
    end
  end

  def edit
    @inventory_item = current_company.inventory_items.find(params[:id])
  end

  def update
    @inventory_item = current_company.inventory_items.find(params[:id])

    if @inventory_item.update_attributes(inventory_item_params)
      redirect_to inventory_items_path, notice: 'Inventory was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @inventory_item = current_company.inventory_items.find(params[:id])
    @inventory_item.destroy

    redirect_to inventory_items_path
  end

private

  # Never trust parameters from the scary internet, only allow the white list through.
  def inventory_item_params
    params.require(:inventory_item).permit(:company_id, :description, :serial_number, :quantity, :tag_list,
                                           :new_unit_type)
  end
end

app/views/inventory_items/_form.html.haml
= form_for(@inventory_item) do |f|
  = render 'shared/error_messages', object: f.object
  = f.hidden_field :company_id, value: current_company.id

  .row
    .small-12.medium-6.large-6.columns
      = f.label :description
      = f.text_field :description, autofocus: true
    .small-12.medium-6.large-6.columns
      = f.label :quantity
      = f.number_field :quantity, step: 0.001, placeholder: '0.000'

  .row
    .small-12.medium-6.large-6.columns
      = f.label :serial_number
      = f.text_field :serial_number

  .panel
    .row
      .small-12.medium-6.large-6.columns
        = f.label :tag_list, 'Tags (separate by commas)'
        = f.text_field :tag_list, placeholder: 'Create new tag(s) or use available tags.'
      .small-12.medium-6.large-6.columns
        %b Available tags:
        = current_company.available_tags

  .row
    .small-12.medium-6.large-6.columns
      = f.submit class: 'button radius expanded'

app/views/inventory_items/edit.html.haml
- provide(:title, 'Edit Inventory Item')

.row
  .small-12.columns
    %h1.main_page_header Editing Inventory Item
    %br/

    = render 'form'

    = link_to 'Back', inventory_items_path

app/views/inventory_items/index.html.haml
- provide(:title, 'Inventory Items')

.row
  .small-12.columns
    .pad-top
      %ul.inline-list
        %li= link_to 'New Inventory Item', new_inventory_item_path, class: 'small button radius'
        - if params[:tag]
          %li= link_to 'Clear Search', inventory_items_path, class: 'small button radius alert'

    #tag_cloud
      - tag_cloud current_company.tag_counts, %w[s m l] do |tag, css_class|
        = link_to tag.name, tag_path(tag.name), class: css_class

    %h1.main_page_header= "#{current_company.name} Inventory Items"

    .scroll_overflow-x
      %table
        %thead
          %tr
            %th Description
            %th Quantity
            %th Serial number
            %th Tags
            %th Edit
            %th Destroy

        %tbody
          - @inventory_items.each do |inventory_item|
            %tr
              %td= link_to inventory_item.description, inventory_item_path(inventory_item)
              %td= sprintf('%g' % inventory_item.quantity)
              %td= inventory_item.serial_number
              %td= raw inventory_item.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ')
              %td.center_cell
                = link_to edit_inventory_item_path(inventory_item) do
                  %i.fas.fa-edit
              %td.center_cell
                = link_to inventory_item, class: 'red_link', method: :delete,
                data: { confirm: t(:confirm_delete_inventory_item) } do
                  %i.fas.fa-trash

    = paginate @inventory_items

app/views/inventory_items/new.html.haml
- provide(:title, 'New Inventory Item')

.row
  .small-12.columns
    %h1.main_page_header New Inventory Item
    %br/

    = render 'form'

    = link_to 'Back', inventory_items_path

app/views/inventory_items/show.html.haml
- provide(:title, raw(@inventory_item.description))

.row
  .small-12.columns
    %h3.main_page_header= @inventory_item.description
    %br/

    %p
      %b Quantity:
      = sprintf('%g' % @inventory_item.quantity)

    %p
      %b Serial number:
      = @inventory_item.serial_number

    %p
      %b Tags:
      = @inventory_item.tag_list

    = link_to 'Edit', edit_inventory_item_path(@inventory_item)
    |
    = link_to 'Back', inventory_items_path