config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => { :registrations => 'users/registrations', :invitations => 'users/invitations' }

  resource :company do
    member do
      get :search_invoices
      get :about
      delete 'delete_user/:id', to: 'companies#delete_user', as: :delete_user
    end
  end

  get :dashboard, to: 'dashboard#home'
  get 'dashboard/developer', as: :developer_dashboard
  get 'dashboard/developer/:all_users', to: 'dashboard#developer', as: :all_users

  resources :accounts do
    post :invite_customer, on: :member
  end

  resources :services, except: [:show, :index, :new] do
    collection do
      post :dashboard_create
      post :invoice_create
      get :history_search
    end
  end

  resources :invoices do
    collection do
      post :apply_checked_services_create
    end
    member do
      get :invoice_ready
      patch :change_account_header
      patch :apply_services_update
      patch :remove_services_update
    end
    resources :payments, except: [:show, :index]
  end

  resources :reports, only: [:index] do
    collection do
      get :income
      get 'income/accounts', to: 'reports#income_accounts'
      get 'income/line_graph', to: 'reports#income_line_graph'
      get 'income/bar_graph', to: 'reports#income_bar_graph'
    end
  end

  resources :inventory_items
  get 'search_tag/:tag', to: 'inventory_items#index', as: :tag

  get :about, to: 'welcome#about'
  get :contact_us, to: 'welcome#contact_us'
  get 'sitemap.xml', to: 'welcome#sitemap', format: :xml, as: :sitemap

  root to: 'welcome#home'
end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :company
  
  # Keeping belongs_to, accepts_nested_attrubtes_for and attr_accessible all
  # in one place because they are all related to the User.
  belongs_to :user, dependent: :delete
  accepts_nested_attributes_for :user

  has_many :services, dependent: :destroy
  has_many :invoices, dependent: :destroy
  has_many :payments

  validates :name, presence: true
  validate :company_account_name_unique

  scope :by_name, -> { order('name ASC') }
  scope :by_recent_activity, -> { order('updated_at DESC') }
  scope :with_limit, -> { limit(5) }

  def full_address
    [address_1, address_2, city, state, zip].select(&:present?).join(', ')
  end

  def sum_services(view_by, active_date)
    services.by_selected_range(view_by, active_date).sum(:cost)
  end

  def sum_invoiceable_services
    services.by_invoiceable.sum(:cost)
  end

  def total_account_payments(view_by, active_date)
    payments.by_selected_range(view_by, active_date).sum(:amount)
  end

  def all_services_invoiced?
    !services.by_invoiceable.present?
  end

  def paid_in_full?
    invoices.all?(&:paid_in_full?)
  end

  def total_outstanding_invoices
    invoices.by_outstanding.sum(&:balance_due)
  end

private

  # Check for Company Account name uniqueness.
  def company_account_name_unique
    errors.add(:name, 'already exists') if name && account_name_exists?
  end

  # If account is being updated, find the current account the user is updating and remove that account's name
  # from the array. Then check if the form [name] being submitted is present. This allows account to be updated
  # while validating the form [name] submitted is unique.
  # If account is being created, there is no [id], and no names will be removed from the array.
  def account_name_exists?
    (company.accounts.pluck(:name) - [current_account.try(:name)]).include?(name)
  end

  # Use find_by :id method so if there is no [id] present, current_account returns nil.
  def current_account
    @current_account ||= company.accounts.find_by(id: self.id)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_owner!, only: [:destroy]
  before_action :require_admin!, except: [:edit, :update, :destroy]
  before_action :authenticate_account!, except: [:index, :new, :create]
  before_action :load_account, only: [:show, :edit, :update, :destroy, :invite_customer]

  def index
    @accounts = current_company.accounts.by_name.page(params[:page]).per(10).includes(:invoices, :user)
  end

  def show
    @service = @account.services.build
    @service.performed_on ||= Date.current
    @services = @account.services.includes(:invoice)
    @invoice = @account.invoices.build
    @invoice.established_at ||= Date.current
    @invoice.sales_tax ||= current_company.sales_tax
    @invoices = @account.invoices.includes(:payments, :account).by_outstanding
  end

  def new
    @account = current_company.accounts.build
    @account.build_user
  end

  def create
    @account = current_company.accounts.build(account_params)
    @account.user.company_id = current_company.id
    @account.user.skip_validation = true

    if @account.save
      redirect_to @account, notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  def edit
    @invoice = current_company.invoices.find_by(id: params[:invoice_id])
  end

  def update
    @account.user.skip_validation = true
    @invoice = current_company.invoices.find_by(id: params[:invoice_id])

    if @account.update_attributes(account_params)
      redirect_account_or_invoice
    else
      render :edit
    end
  end

  def destroy
    @account.destroy
    redirect_to accounts_url, alert: 'Account and all account information was successfully deleted.'
  end

  def invite_customer
    @account.user.invite!(current_user)  # current user is optional to set the invited_by attribute
    redirect_to account_path(@account), notice: 'Successfully sent invitation.'
  end

private

  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require(:account).permit(:address_1, :address_2, :city, :fax, :name, :phone, :state, :zip,
                                    :uses_account_name, :uses_contact_name, :prefix, :postfix, :divider,
                                    user_attributes: [:id, :email, :password, :password_confirmation, :remember_me, :name])
  end

  def authenticate_account!
    redirect_to root_path if current_account.nil?
  end

  def load_account
    @account = current_account
  end

  def redirect_account_or_invoice
    if @invoice
      redirect_to edit_invoice_path(@invoice), notice: 'Account was successfully updated.'
    elsif current_user.is_admin?
      redirect_to @account, notice: 'Account was successfully updated.'
    else
      redirect_to root_path, notice: 'Your account was successfully updated.'
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def invoiceable_or_not(account)
    case account.all_services_invoiced?
    when true
      'Yes'
    else
      link_to 'No', account_path(account, anchor: :invoiceable)
    end
  end

  def pif_or_outstanding(account)
    case account.paid_in_full?
    when true
      'Yes'
    else
      link_to 'No', account_path(account, anchor: :outstanding)
    end
  end
end

app/views/accounts/_checkbox_fields.html.haml
.small-12.medium-6.large-6.columns
  %label Used on Invoices:

  %ul.inline-list.pad-top
    %li
      %label
        = f.check_box :uses_account_name
        Account/Company name
    %li
      %label
        = f.check_box :uses_contact_name
        Contact's (Full name)

app/views/accounts/_contact_info_modal.html.haml
%div{id: "contactInfoModal#{account.id}", class: 'reveal large', data: { reveal: true }}
  %h1
    = account.name
    %small Contact Information

  %hr/

  %ul.menu.vertical
    %li
      %label
        %b Address:
        = account.full_address
    %li
      %label
        %b Phone:
        = account.phone
    %li
      %label
        %b Fax:
        = account.fax
    %li
      %label
        %b Email:
        = mail_to account.user.email, nil, target: '_blank'
  %button.close-button{aria: {label: 'Close modal'}, data: {close: true}, type: 'button'}
    %span{aria: {hidden: 'true'}} ×

app/views/accounts/_edit_customer_header.html.haml
.row
  .small-12.columns
    .float-right
      = link_to edit_account_path(current_account), title: 'Edit Account' do
        Edit ACCT
        %i.fas.fa-edit

      - if current_user.is_owner?
        = link_to current_account, title: 'Delete Account', class: 'pad-left red_link', method: :delete,
        data: { confirm: t(:confirm_delete_account) } do
          Delete ACCT
          %i.fas.fa-trash

.row
  .small-12.columns
    %h4= "#{current_account.name} Account"

    = render 'shared/customer_header'

app/views/accounts/_form.html.haml
= form_for(@account) do |f|
  = render 'shared/error_messages', object: f.object
  = hidden_field_tag :invoice_id, @invoice.id if @invoice

  - if current_user.is_admin?
    .row
      .small-12.medium-6.large-6.columns
        = f.label :name
        = f.text_field :name, placeholder: 'Smith House'

      = render 'accounts/checkbox_fields', f: f

  = f.fields_for(:user, @account.user) do |user_f|
    .row
      .small-12.medium-6.large-6.columns
        = user_f.label :name, "Contact's (Full name)"
        = user_f.text_field :name, placeholder: 'John Smith'

      .small-12.medium-6.large-6.columns
        = user_f.label :email
        = user_f.text_field :email, title: edit_email_address(@account.user),
          disabled: @account.user.encrypted_password.present?

  = render 'shared/address_fields', f: f
  = render 'accounts/pre_post_fields', f: f if current_user.is_admin?

  .row
    .small-12.medium-6.large-6.columns
      = f.submit class: 'button radius expanded'

app/views/accounts/_invite_customer_modal.html.haml
%div{id: "inviteCustomerModal#{account.id}", class: 'reveal large', data: { reveal: true }}
  %h1 Invitation Preview

  %hr/

  .disable_link= render 'devise/mailer/customer', resource: account.user

  %hr/

  = link_to 'Send Invitation', invite_customer_account_path(account), method: :post, class: 'tiny button radius'
  %button.close-button{aria: {label: 'Close modal'}, data: {close: true}, type: 'button'}
    %span{aria: {hidden: 'true'}} ×

app/views/accounts/_invoice_ready_modal.html.haml
%div{id: "invoiceReadyModal#{invoice.id}", class: 'reveal large', data: { reveal: true }}
  %h1 Notification Preview
  %hr/

  .disable_link= render 'user_mailer/invoice_ready_message', invoice: invoice
  %hr/

  = link_to 'Send Notification', invoice_ready_invoice_path(invoice), class: 'tiny button radius'
  %button.close-button{aria: {label: 'Close modal'}, data: {close: true}, type: 'button'}
    %span{aria: {hidden: 'true'}} ×

app/views/accounts/_outstanding_invoices.html.haml
.outline
  %h4 Outstanding Invoices

  = render 'invoices/table'

  .label_size=link_to "All #{@account.name} Invoices", invoices_path

app/views/accounts/_pre_post_fields.html.haml
#format_invoice_number.anchor
.outline
  .row
    .small-12.columns
      %p.label_size
        %b Format Account Invoice Number Option -
        %br/
        You can format a Prefix and/or Postfix to all of this Account's Invoice numbers.

      %p.label_size
        %b Examples:
        %br/
        [Prefix = "ROOF"] [Postfix = "JOB"] =
        %b ROOF###JOB
        %br/
        [Prefix = "Home"] [Divider = "-"] =
        %b Home-###
        %br/
        If you want something like
        %b ROOF ### JOB
        just enter a space in the Divider.

  .row
    .small-4.medium-3.large-3.columns
      = f.label :prefix
      = f.text_field :prefix, placeholder: 'Prefix'

    .small-4.medium-3.large-3.center.columns
      .down_to_text_field
        [INVOICE#]

    .small-4.medium-3.large-3.columns
      = f.label :postfix
      = f.text_field :postfix, placeholder: 'Postfix'

    .hide-for-small-only.medium-1.large-1.center.columns
      .down_to_text_field
        |

    .small-2.medium-2.large-2.left.columns
      = f.label :divider
      = f.text_field :divider, placeholder: 'Divider'

app/views/accounts/_table.html.haml
.scroll_overflow-x
  %table
    %thead
      %tr
        %th= 'Account'.pluralize(@accounts.count)
        %th Contact name
        %th Contact info
        %th All services invoiced
        %th All invoices P.I.F.
        %th User status
        %th Edit
        - if current_user.is_owner?
          %th Destroy
    %tbody
      - @accounts.each do |account|
        %tr
          %td= link_to account.name, account
          %td= account.user.name
          %td.center_cell
            %button.to_link{data: { open: "contactInfoModal#{account.id}" }}
              %i.fas.fa-envelope
          %td{class: "no_action_required_#{account.all_services_invoiced?}"}
            = invoiceable_or_not(account)
          %td{class: "no_action_required_#{account.paid_in_full?}"}
            = pif_or_outstanding(account)
          %td.center_cell= render 'accounts/user_status', account: account
          %td.center_cell
            = link_to edit_account_path(account) do
              %i.fas.fa-edit
          - if current_user.is_owner?
            %td.center_cell
              = link_to account, class: 'red_link', method: :delete, data: { confirm: t(:confirm_delete_account) }  do
                %i.fas.fa-trash
        = render 'accounts/contact_info_modal', account: account

app/views/accounts/_user_status.html.haml
- if account.user.invitation_token.present?
  Invited
  %button.tiny.radius.user_status_button.button{                              |
  data: { open: "inviteCustomerModal#{account.id}" },                         |
  title: 'to view there account information'} Re-invite                       |

  = render 'accounts/invite_customer_modal', account: account

- elsif account.user.encrypted_password.present?
  %b.green_text Active

  - if @invoice && @invoice.persisted?
    %br/
    %button.tiny.radius.send_user_email_button.button{                        |
    data: { open: "invoiceReadyModal#{@invoice.id}" }                         |
    } Notify #{@invoice.account.user.name} that invoice is ready for viewing  |

    = render 'accounts/invoice_ready_modal', invoice: @invoice

- elsif account.user.email.present?
  %button.tiny.radius.user_status_button.button{                              |
  data: { open: "inviteCustomerModal#{account.id}" },                         |
  title: 'to view there account information'} Invite                          |

  = render 'accounts/invite_customer_modal', account: account

- else
  no email

app/views/accounts/edit.html.haml
- provide(:title, 'Edit Account')

.row
  .small-12.columns
    %h1.main_page_header= "Editing #{@account.name} Account"
    %br/

    = render 'form'

    = link_to "#{@account.name} Account", account_path(@account), class: 'small button radius'

app/views/accounts/new.html.haml
- provide(:title, 'New Account')

.row
  .small-12.columns
    %h1.main_page_header New Account
    %br/

    = render 'form'

    %ul.inline-list
      %li= link_to 'Dashboard', root_path, class: 'small button radius'
      %li= link_to 'Accounts Listing', accounts_path, class: 'small button radius'

app/views/accounts/service_history_search.html.haml
- provide(:title, raw("#{@account.name} Account"))

.row
  .small-12.columns
    %br/

    .outline
      .row
        .small-8.columns
          %h4= "#{@account.name} Account"

        .small-4.columns
          .pad-top.right
            = link_to edit_account_path(@account), title: 'Edit Account' do
              %i.page.fi-page-edit
            - if current_user.is_owner?
              = link_to @account, title: 'Delete Account', method: :delete,
              data: { confirm: 'Are you sure? This will permanently DELETE your ACCOUNT information and all SERVICES, INVOICES, and PAYMENTS applied to the ACCOUNT!' } do
                %i.general.fi-x
      .row
        .small-12.columns
          = render 'shared/customer_header'

    .outline= render 'services/history'

    %br/

    %ul.inline-list
      %li= link_to 'Account Listings', accounts_path, class: 'small button radius'
      %li= link_to "#{@account.name} Invoices", invoices_path, class: 'small button radius'

app/views/accounts/show.html.haml
- provide(:title, raw("#{@account.name} Account"))

.row
  .small-12.columns
    %br/

    .outline= render 'accounts/edit_customer_header'

    .outline= render 'services/new'

    = render 'invoices/invoiceable' if @services.by_invoiceable.any?

    = render 'invoices/outstanding'

    = render 'services/recent_history'

    %br/

    %ul.inline-list
      %li= link_to 'Account Listings', accounts_path, class: 'small button radius'